services:
  recorder:
    profiles:
      - jobs
    image: haberrj/avian-acoustic-monitoring:latest
    container_name: avian_recorder
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    volumes:
      - ./recordings:/app/recordings
      - ./debug_recordings:/app/debug_recordings
      - ./logs:/app/logs
    restart: "no"
    command: ["python", "-m", "src.pipeline"]

  db:
    image: postgres:15
    container_name: acoustic_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  migrate:
    profiles:
      - jobs
    environment:
      - POSTGRES_HOST=db
    image: haberrj/avian-acoustic-monitoring:latest
    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "src/storage/migrate.py"]

  dashboard:
    environment:
      - POSTGRES_HOST=db
    image: haberrj/avian-acoustic-monitoring:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: [
      "streamlit",
      "run",
      "dashboard/app.py",
      "--server.port=3000",
      "--server.address=0.0.0.0"
    ]
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: avian_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - dashboard


volumes:
  postgres_data: