"""add stations

Revision ID: f341b2e00f37
Revises: 
Create Date: 2026-06-22 13:07:14.413490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f341b2e00f37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detections', 'stations', ['station_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_column('detections', 'station_id')
    # ### end Alembic commands ###
